name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20 x64
        uses: actions/setup-node@v3
        with:
          node-version: 20
          architecture: x64
      
      - name: Prepare
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build showcase
        run: npm run build:showcase

      - name: Run unit tests
        run: npm run test -- ngx-maplibre-gl --watch=false --no-progress --browsers=ChromeHeadless

      - name: Run lint
        run: npm run lint
        
      - name: Run e2e tests
        run: npm run e2e

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/videos
        if: ${{ failure() }}
