name: Github pages push

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      # Runs a set of commands using the runners shell
      - name: Install and build
        run: |
          npm ci
          npm run build:showcase
          npm run docs
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/showcase/
